# Generated by Django 3.0.5 on 2020-04-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20200428_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='topping',
        ),
    ]
