# Generated by Django 3.0.5 on 2020-05-01 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.Pizza')),
            ],
        ),
        migrations.DeleteModel(
            name='comment',
        ),
    ]
