# Generated by Django 3.0.6 on 2020-05-04 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0007_auto_20200501_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_comment',
            old_name='name',
            new_name='text',
        ),
    ]
