# Generated by Django 3.0.6 on 2020-05-04 22:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0008_auto_20200504_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
